# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ask.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ask.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\task.proto\"-\n\x08Question\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"&\n\x06\x41nswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0c\n\x04link\x18\x02 \x01(\t2(\n\x06Oracle\x12\x1e\n\x06Reveal\x12\t.Question\x1a\x07.Answer\"\x00\x62\x06proto3')
)




_QUESTION = _descriptor.Descriptor(
  name='Question',
  full_name='Question',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='Question.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='Question.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=58,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='Answer.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link', full_name='Answer.link', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['Question'] = _QUESTION
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Question = _reflection.GeneratedProtocolMessageType('Question', (_message.Message,), dict(
  DESCRIPTOR = _QUESTION,
  __module__ = 'ask_pb2'
  # @@protoc_insertion_point(class_scope:Question)
  ))
_sym_db.RegisterMessage(Question)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), dict(
  DESCRIPTOR = _ANSWER,
  __module__ = 'ask_pb2'
  # @@protoc_insertion_point(class_scope:Answer)
  ))
_sym_db.RegisterMessage(Answer)



_ORACLE = _descriptor.ServiceDescriptor(
  name='Oracle',
  full_name='Oracle',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=100,
  serialized_end=140,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reveal',
    full_name='Oracle.Reveal',
    index=0,
    containing_service=None,
    input_type=_QUESTION,
    output_type=_ANSWER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORACLE)

DESCRIPTOR.services_by_name['Oracle'] = _ORACLE

# @@protoc_insertion_point(module_scope)
