# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ask_pb2 as ask__pb2


class OracleStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Reveal = channel.unary_unary(
        '/Oracle/Reveal',
        request_serializer=ask__pb2.Question.SerializeToString,
        response_deserializer=ask__pb2.Answer.FromString,
        )


class OracleServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Reveal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OracleServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Reveal': grpc.unary_unary_rpc_method_handler(
          servicer.Reveal,
          request_deserializer=ask__pb2.Question.FromString,
          response_serializer=ask__pb2.Answer.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Oracle', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
